### ISSUE TITLE
CORD v0.8.0 Release checklist

### ISSUE THREAD

**Issue by smohan-dw** [dhiway/cord#173]
# Release Checklist

This is the release checklist for CORD v0.8.0. **All** following checks should be completed before publishing a new release. The current release candidate can be checked out with `git checkout release-v0.8.0`

### All Releases

These checks should be performed on the codebase prior to forking to a release-candidate branch.
 
- [x] Verify [`spec_version`](https://github.com/dhiway/blob/develop/doc/release-checklist.md#spec-version) has been incremented since the last release. If the runtime was published (release or pre-release), either the `spec_version` or `impl` must be bumped.
- [x] Verify previously [completed migrations](https://github.com/dhiway/cord/blob/develop/doc/release-checklist.md#old-migrations-removed) are removed.
- [x] Verify pallet and [extrinsic ordering](https://github.com/dhiway/cord/blob/develop/doc/release-checklist.md#extrinsic-ordering) has stayed the same. Bump `transaction_version` if not.
- [x] Verify [benchmarks](https://github.com/dhiway/cord/blob/develop/doc/release-checklist.md#benchmarks) have been updated for any modified runtime logic.
- [x] Verify builds are done using the production profile

The following checks can be performed after we have forked off to the release-candidate branch or started an additional release-candidate branch (rc-2, rc-3, etc)

- [x] Verify [new migrations](https://github.com/dhiway/cord/blob/develop/doc/release-checklist.md#new-migrations) complete successfully, and the runtime state is correctly updated.
- [x] Verify [CORD SDK & API](https://github.com/dhiway/cord/blob/develop/doc/release-checklist.md#polkadot-js) are up to date with the latest runtime changes.
- [x] Push runtime upgrade to Sprintnet and verify network stability.
- [x] Verify Docker images are published
